apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lkc.magnet.fullname" . }}
spec:
  serviceName: {{ include "lkc.magnets.serviceName" . }}
  replicas: {{ .Values.magnet.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lkc.magnet.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "lkc.magnet.fullname" . }}
    spec:
      containers:
        - name: magnet
          image: "{{ .Values.magnet.image.repository }}:{{ default .Chart.AppVersion .Values.magnet.image.tag }}"
          imagePullPolicy: {{ .Values.magnet.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: RING_SIZE
              value: "{{ .Values.magnet.replicaCount }}"
            - name: RING_BASENAME
              value: "{{ include "lkc.magnet.fullname" . }}"
            - name: RING_SERVICE
              value: "{{ include "lkc.magnets.serviceName" . }}"
            - name: EXPERIMENT_URL
              value: "http://{{ include "lkc.experiment.fullname" . }}:8080/observe"
